language: node_js
sudo: false
cache:
  directories:
    - "node_modules"
node_js:
  - "6"
branches:
  only:
    - master
notifications:
  email: false
script:
  - npm run validate
deploy:
  provider: surge
  project: ./
  domain: wages.surge.sh
  skip_cleanup: true
